### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [c0nf1den71al/wagyu-xss#10]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@gloomless) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by c0nf1den71al** [comment]
Good Morning, 

Thanks for raising this issue. I have now created a `SECURITY.md` file in the main branch which outlines how to deal with vulnrabilities.

I will leave this issue open until I receive your email as I have only just created the forwarding rule.

Thanks 😃

**Comment by c0nf1den71al** [comment]
Email communication received. Closing.
